### ISSUE TITLE
Launching Photoshop crashes the whole system

### ISSUE THREAD

**Issue by realgamebreaker** [shvedes/photoshop-linux#2]
The install went fine but when I try to launch Photoshop the init window comes up and after it's finished the system hangs (not a kernel panic but unresponsive, can't even switch to another tty). I can see that the init process was finished because it hung during the close animation of the window

- Arch Linux
- KDE plasma
- wine 9.19-1
- Wayland
- AMDGPU

**Comment by shvedes** [comment]
Looks weird. Can you confirm that it's not an OOM situation?

**Comment by realgamebreaker** [comment]
> Looks weird. Can you confirm that it's not an OOM situation?

I don't think so because I have 16gigs, didn't have any memory heavy apps running, and also have some swap set up

**Comment by shvedes** [comment]
> I don't think so because I have 16gigs

Do you think so, or can you say for sure that this is not OOM? Also, if you can, please launch `photosgop.sh` directly from terminal and paste wine output here

**Comment by realgamebreaker** [comment]
Where is that file?

> > I don't think so because I have 16gigs
> 
> Do you think so, or can you say for sure that this is not OOM? Also, if you can, please launch `photosgop.sh` directly from terminal and paste wine output here

**Comment by shvedes** [comment]
`$HOME/.local/bin/photoshop.sh`. I want to move this file to its own subfolder in the future tho

**Comment by realgamebreaker** [comment]
Weird. the photoshop.sh file seems empty and I can't get it to launch anymore.
Give me a minute I'll reinstall

**Comment by shvedes** [comment]
> the photoshop.sh file seems empty

Impossible, since as you said you saw Photoshop's first splash screen. This means that script launched as it should

**Comment by realgamebreaker** [comment]
It now launches but linux still crashes after it's open for a few seconds. Here's the wine log:
[log.log](https://github.com/user-attachments/files/17365778/log.log)
EDIT: It doesn't crash when it's open and I don't do anything. It only crashes when I try to switch to another application (ALT-TAB, or clicking)

**Comment by shvedes** [comment]
Try this:

```bash
env WINEDLLOVERRIDES="d3d12.dll=d,d3d12core=d" $HOME/.local/bin/photoshop.sh
```

**Comment by shvedes** [comment]
Also, do you have `LIBVA_DRIVER_NAME` and `VDPAU_DRIVER` environment variables?

**Comment by shvedes** [comment]
Looks like you have a rendering issue. Did you installed your GPU drivers and wine dependencies properly ([ArchWiki page](https://wiki.archlinux.org/title/AMDGPU))?
For full list of wine dependencies you can run `pacman -Qi wine`

**Comment by realgamebreaker** [comment]
The dll overrides made it error out because it couldn't find those dlls.
I had my gpu drivers installed correctly but I don't have these enviroment variables despite having both packages installed (As seen in the picture).
![image](https://github.com/user-attachments/assets/5ea62594-0726-49c6-a610-29bc4942fbc4)

**Comment by shvedes** [comment]
Set up this environments in shell settings or in `/etc/profile.d/` as [ArchWiki](https://wiki.archlinux.org/title/Hardware_video_acceleration#Configuring_VA-API) says. 

Here's  mine for example:

```bash
[ shved$huawei ~ ]$ cat /etc/profile.d/user-defined.sh | grep radeon
export LIBVA_DRIVER_NAME="radeonsi"
export VDPAU_DRIVER="radeonsi"
```

**Comment by shvedes** [comment]
@realgamebreaker did you solve this?

**Comment by realgamebreaker** [comment]
> @realgamebreaker did you solve this? 

I'm on vacation right now. Will try when I get back home.

**Comment by shvedes** [comment]
Okay, no problem

**Comment by shvedes** [comment]
@realgamebreaker Any updates? Can i close the issue?

**Comment by realgamebreaker** [comment]
> @realgamebreaker Any updates? Can i close the issue?

Oh yeah sorry I forgot about this
