### ISSUE TITLE
Text Layers/Tool are very slow

### ISSUE THREAD

**Issue by M0untacir** [shvedes/photoshop-linux#6]
Hi.
I managed to make it work. All options on the Advanced Graphics Processor Settings are working.
The problem am having is that selecting any text layer take seconds, also selecting the text is very slow and laggy especially with variable fonts.
I tried multiple photoshop versions, the only version that did not have this problem is CS6.

Do you have any idea how to fix it?

_Linux Mint 22 Cinnamon
6.8.0-49-generic
wine-9.0 (Ubuntu 9.0~repack-4build3)
Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]_

Thank you.

**Comment by shvedes** [comment]
Yeah, can reproduce this (wine, proton, cachyos-proton, whatever). Anyway, i don't thnik i can do something with it. Also, isn't Photoshop itself performing slow with any text layers, even on Windows?

**Comment by M0untacir** [comment]
It gets slow with a lots of text layers but not as with wine, the tool stays snappy.
I did some comparisons with windows, and it looks like only the UI is GPU-accelerated on wine, not the canvas. The CPU is almost not used in windows, while it goes wild on wine when interacting with the canvas (zoom,pan,text selection...).
Thank you very much

**Comment by shvedes** [comment]
I can't do anything with it, sorry.
